name: task_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
dependency_overrides: 
  intl: ^0.18.0
dependencies:
  auto_route: ^6.1.0
  awesome_notifications: ^0.7.4+1
  bloc: ^8.1.1
  calendar_time: ^2.2.0
  dart_date:
    git:
      url: https://github.com/spaznuski/dart_date.git
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_expandable_fab: ^1.7.1
  flutter_localizations:
    sdk: flutter
  fpdart: ^0.5.0
  freezed: any
  freezed_annotation: any
  get_it: ^7.2.0
  hive: ^2.2.3
  intl: ^0.18.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0
  json_annotation: any
  json_serializable: any
  logger: ^1.3.0
  path_provider: ^2.0.14
  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.6
  table_calendar: ^3.0.9
  timelines: ^0.1.0
  uuid: ^3.0.7
  visibility_detector: ^0.4.0+2

dev_dependencies:
  auto_route_generator: ^6.2.0
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  generate: true
