// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZwGEBkJ1xDc-QOt2nhWxFajT-hDfG8gw',
    appId: '1:448258805378:web:bc946f3e5f9850d49b2e9b',
    messagingSenderId: '448258805378',
    projectId: 'tasktail-4bba9',
    authDomain: 'tasktail-4bba9.firebaseapp.com',
    storageBucket: 'tasktail-4bba9.appspot.com',
    measurementId: 'G-BMTPFG3GT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrLeUxw8DPYivXPimcZbs1tLkIbST0PAQ',
    appId: '1:448258805378:android:ef1d8f46e772ca079b2e9b',
    messagingSenderId: '448258805378',
    projectId: 'tasktail-4bba9',
    storageBucket: 'tasktail-4bba9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLvzT5P8s8dFS7dQi3OUJwbxBLN4soPvA',
    appId: '1:448258805378:ios:24d6a2496f1fb98c9b2e9b',
    messagingSenderId: '448258805378',
    projectId: 'tasktail-4bba9',
    storageBucket: 'tasktail-4bba9.appspot.com',
    iosClientId:
        '448258805378-2tp491aiso2vup4ijdmq4mddnesn2dum.apps.googleusercontent.com',
    iosBundleId: 'com.canavci95.taskapp.stg',
  );
}
